### ISSUE TITLE
`Highlight.code` not available

### ISSUE THREAD

**Issue by augustwester** [appstefan/HighlightSwift#1]
`Highlight.code(text)` (as referenced in the readme) doesn't seem to be available. I'm getting the following error:

```
Type 'Highlight' has no member 'code'
```

Am I missing something or is this an error in the documentation? Thanks 🙏

**Comment by augustwester** [comment]
Ah, I'm assuming what is meant in the readme is `Highlight.text(code)`. At least this seems to work.

**Comment by appstefan** [comment]
Yes the readme is out-of-date, good spot. Opted to switch it to `Highlight.text(code)` but open to suggestions. I will update now. Thanks!
