### ISSUE TITLE
Returns `undefined` if language isn't supported

### ISSUE THREAD

**Issue by augustwester** [appstefan/HighlightSwift#2]
Hi again 😄

I've been toying around with the library and it's very useful! However, I've noticed that `Highlight.text(code, language: language)` outputs an AttributedString containing `undefined` if you supply a language that isn't supported. For instance, this seems to be the case for something like the following:

```swift
Highlight.text("some fancy code", language: "pascal")
```

It would be great if the library simply fell back to a plain, non-highlighted AttributedString in such cases. Do you agree?

**Comment by appstefan** [comment]
Hi there, I'm glad it's been useful!
100% agree, it makes more sense to return a plain copy of the input string in that case.

I just got around to publishing a new release (1.0.6) and this is one of the many improvements it includes. 👍
